require("core.plugin_config.which_keys")
require("core.plugin_config.LSP")
require("core.plugin_config.Fuzzy")
require("core.plugin_config.Directory")
require("core.plugin_config.BCE")
require("core.plugin_config.treesitter")
